name: Deploy via FTP

on: push

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftpupload.net
        port: 21
        username: $if0_41595226
        password: Loi159357216132
