name: Deploy via FTP
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftpupload.net
        port: 21
        username: $if0_41595226
        password: Loi159357216132
